### ISSUE TITLE
Dataset path

### ISSUE THREAD

**Issue by saikumarkethi** [sdjsngs/Re-implement-Memorizing-Normality-to-Detect-Anomaly#1]
Can you tell me where can i give path of avenue or uscd dataset in you code
and my path is "/content/drive/MyDrive/UCSD_Anomaly_Dataset/UCSDped1/Train"

**Comment by sdjsngs** [comment]
the hyper-parameter in this work is defined in config/default.py and configs/xx.yaml  and the  merge them in utils/parser.py.
You can define the datapath in UCSD-Ped2.yaml   PED.PATH_TO_DATA_DIR  or in the default.py ， but the yaml file will cover the default.py in parser.py  you can also check the code in dataset/UCSDPed2.py  __init__   self.data_root=cfg.PED.PATH_TO_DATA_DIR .

**Comment by saikumarkethi** [comment]
File "/content/Re-implement-Memorizing-Normality-to-Detect-Anomaly/train.py", line 8, in <module>
    from net.dataset.loader import construct_loader
  File "/content/Re-implement-Memorizing-Normality-to-Detect-Anomaly/net/dataset/__init__.py", line 5, in <module>
    from .Avenue import Avenue # noqa
ModuleNotFoundError: No module named 'net.dataset.Avenue'

**Comment by sdjsngs** [comment]
check the parser.py  func parse_args()   the default value in add_argument for cfg_file

**Comment by sdjsngs** [comment]
pycharm  net folder  mark dierctory as sources root

**Comment by sdjsngs** [comment]
you can check this https://github.com/facebookresearch/SlowFast for more detail

**Comment by saikumarkethi** [comment]
> you can check this https://github.com/facebookresearch/SlowFast for more detail

**Comment by saikumarkethi** [comment]
Sir can if you give readme file for your code that will be very useful

**Comment by saikumarkethi** [comment]
Sir i have did everything what you have said in readme file still having issues can you please reply to my mail (kethi.saikumar9@gmail.com) i am having some doubts
